### ISSUE TITLE
Change enum methods to use actual Enum data type

### ISSUE THREAD

**Issue by wilr** [silverstripe/silverstripe-postgresql#17]
Currently, enums are created in Postgres by creating the field as a varchar and then imposing a constraint upon the field, thereby creating a pseudo-enum. This let older versions of Postgres use SilverStripe.

It's highly likely that we'll be creating a fancy system for detecting and creating or modifying indexes, which are held database-wide. Index names need to be unique.

Enums have the same problems and the solution we come up with for indexes will also apply to enum fields. We should drop the constraint method and use a proper enum datatype to achieve enum functionality.

**Comment by dhensby** [comment]
I think the general consensus (or at least my will) is to actually move the core *away* from native enums because of their restrictions. Also, doctrine/dbal doesn't support enums and is one of the most comprehensive DB layers available in the PHP ecosystem, so that's got to say something about their suitability ;)
